### PR TITLE
Making diesel integration code backend configurable (#60) (fixes #59)

### LINKED ISSUE #59: Allow using Diesel migrations with SQLite
Hello; the project is very appealing and I'd like to use it to boostrap our database but it seems it cannot be used with Diesel with other backend. Am I wrong?

### PR DESCRIPTION
**Pull request by spacekookie**
This PR addresses #59

This is a first attempt at solving the problem that diesel doesn't
tell us what kind of migration is being run, just demanding an Sql
back from us. We could probably fix this in a nicer way on diesel's
side (i.e. changing the API) but that is a lot more work that just
getting it to work now.

This change assumes that `barrel` is only being compiled with a single
feature, meaning that whenever adding `barrel` to your `diesel` setup,
you can only select one backend.

A few things are still to do:

- [x] This will break CI since we test with `--all-features`
- [x] Update the diesel guide to include all of this
- [ ] Do some manual testing

### CODE REVIEW

File: src/integrations/diesel.rs [hunk 1]
```diff
@@ -99,23 +108,25 @@ fn run_barrel_migration(migration: &Path) -> (String, String) {
...
-[dependencies]
-barrel = { git = \"https://github.com/spacekookie/barrel\", features = [\"pg\"]  }",
-        )
-        .unwrap();
+[dependencies]"
+        .into();
+
+    toml.push_str("barrel = { version = \"*\", features = [ ");
+    toml.push_str(&format!("{}", feat)); // Not sure why format strings are being weird here
+    toml.push_str(" ] }");
```
Comment (otavio) [inline src/integrations/diesel.rs]: The full `toml` could be generated using format! and avoid the multiple  `push_str` calls and make it easier to read.

File: src/integrations/diesel.rs [hunk 2]
```diff
@@ -130,21 +141,22 @@ extern crate barrel;
 use barrel::*;
 
 // FIXME: Make the backend configurable
```
Comment (otavio) [inline src/integrations/diesel.rs]: The fixme could be dropped.

File: src/integrations/diesel.rs (hunk 1 above)
Comment (spacekookie) [reply src/integrations/diesel.rs]: The problem I ran into was that the `format!` string got confused with the `{` in ways I didn't really know how to escape.

You're right, it would be much nicer to read in one block. I might take another stab at this. But it wasn't super trivial unfortunately :confused:
